Repository DeveloperAcademy-POSTECH/MacC-Team13-SplitIt, pull requests merged in 2023-11, with the labels that each got.

#155 Feat/#151 SplitMethodView 구현 완료하였습니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Assets.xcassets/Images/Pictogram/Contents.json
  SplitIt/Assets.xcassets/Images/Pictogram/Pictogram.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Pictogram/Pictogram.imageset/Pictogram@1x.png
  SplitIt/Assets.xcassets/Images/Pictogram/Pictogram.imageset/Pictogram@2x.png
  SplitIt/Assets.xcassets/Images/Pictogram/Pictogram.imageset/Pictogram@3x.png
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/SplitMethodSelect/View/SplitMethodSelectVC.swift
  SplitIt/Presenter/SplitMethodSelect/ViewModel/SplitMethodSelectVM.swift
Labels: ✨ Feat

#157 Feat/#134 ExclItemInfo 관련 뷰를 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Models/LocalModels/ExclItem.swift
  SplitIt/Models/LocalModels/ExclMember.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemAddCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInfo.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputEmptyView.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclMemberSection.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/ViewModel/ExclItemInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/Cell/ExclItemInfoDeactiveModalCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/Cell/ExclItemInfoModalCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoModalSection.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExcltemInfoModalAlertVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoAddModalVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/ExclMemberSection.swift
  SplitIt/Presenter/SplitEditFlow/CSExclItemMemberEdit/ExclMemberEditVM.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/NaviHeader.swift
  SplitIt/Resources/Components/NewSPButton.swift
  SplitIt/Resources/Extensions/UIColor+.swift
Labels: ✨ Feat

#158 Design/#156 SearchView Design을 수정하고 로직을 개선하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@1x.png
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@2x.png
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@3x.png
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/EmptyBackGroundView.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SearchCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
Labels: 🎨 Design

#163 Feat/#161 Createflow에 Customkeyboard를 적용하였습니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoAddModalVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
Labels: ✨ Feat, 🧩 Chore

#167 [Chore/#165] NewSPButton의 필요 없는 코드를 정리하였습니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Resources/Components/NewSPButton.swift
Labels: 🧩 Chore

#170 Chore/#168 차수 종료 시 Realm update 및 splitShareView fetch 수정하였습니다.
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
Labels: 🧩 Chore

#171 [Design/#164] CSMemberSearchView 수정하였습니다.
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/CSMemberCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🎨 Design

#174 Design/#169 Csinfo의 디자인 디테일 적용합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
Labels: ✨ Feat, 🎨 Design

#176 Fix/#175 ExclItemInput 뷰에서 뒤로가기 시 현재 ExclItem관련 데이터를 SplitRepository에서 모두 삭제하도록 수정합니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/ViewModel/ExclItemInputVM.swift
  SplitIt/Repository/SplitRepository.swift
Labels: 🛠️ Fix, 🎨 Design

#178 [Design/#177] NewSPButton의 square type의 디테일을 수정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Resources/Components/NewSPButton.swift
Labels: 🎨 Design

#181 [Feat/#180] `UIDevice+.swift`를 생성하고, `UIFont+.swift`를 수정하였습니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Resources/Extensions/UIDevice+.swift
  SplitIt/Resources/Extensions/UIFont+.swift
Labels: ✨ Feat

#184 Feat/#179 ExclItem의 price logic을 구현합니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoAddModalVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
Labels: ✨ Feat

#186 [Fix/#185] ExclItemModal의 NavigationBar을 SPNavigationBar로 수정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
Labels: 🛠️ Fix

#187 [Design/#172] ShareView Design Detail 수정하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt/Presenter/History/View/HistoryVC.swift
  SplitIt/Presenter/History/ViewModel/HistoryVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionFooter.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Resources/Extensions/UITableView+.swift
Labels: 🎨 Design

#189 [Fix/#188] Edit Flow Method 만들고 확인 완료하였습니다.
  SplitIt/Repository/SplitRepository.swift
Labels: 🛠️ Fix

#192 Fix/#191 csMemberSearchView 정산자가 MemberLog에 포함되던 문제를 해결하였습니다.
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift
Labels: 🛠️ Fix

#195 Fix/#194 csMemberSearchView에서 키보드가 올라올 때 tableView가 가려지던 현상을 수정하였습니다.
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
Labels: 🛠️ Fix

#197 [Feat/#196] HapticManager를 구현하고 csMemberSearchView에 적용하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
  SplitIt/Resources/Utility/HapticManager.swift
Labels: ✨ Feat

#200 Feat/#193 SPAlertController를 구현합니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Resources/Components/NewSPButton.swift
  SplitIt/Resources/Components/SPAlertController.swift
Labels: ✨ Feat

#203 Fix/#199 fix qa update
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Base.lproj/LaunchScreen.storyboard
  SplitIt/Presenter/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Presenter/CustomKeyboard/CustomKeyBoard.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/MyInfo/PayData.swift
  SplitIt/Presenter/MyInfo/SocialPay.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
  SplitIt/Presenter/SplashVC.swift
Labels: 🛠️ Fix

#209 [Fix/#208] 수정 완료
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: 🛠️ Fix

#213 [Fix/#212] SplitShareView 수정하였습니다.
  SplitIt/Presenter/History/View/Cell/HistorySplitCell.swift
  SplitIt/Presenter/History/ViewModel/HistoryVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix

#214 [Feat/#211] CreateFlow에 SPAlertController를 적용합니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/ViewModel/ExclItemInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Resources/Components/SPAlertController.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: ✨ Feat

#216 [Fix/#215] EditFlow의 TotalAmount 관련 로직을 수정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/NewEditFlowViews/EditCSInfo/EditCSInfoVC.swift
  SplitIt/Presenter/SplitEditFlow/NewEditFlowViews/EditCSInfo/EditCSInfoVM.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: ✨ Feat, 🛠️ Fix

#218 Feat/#210 feat customkeyboard
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
  SplitIt/Repository/SplitRepository.swift
Labels: ✨ Feat

#220 [Fix/#217] JSDetail의 영수증 공유하기 버튼의 활성화여부를 수정합니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailVC.swift
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailVM.swift
Labels: 🛠️ Fix

#221 [Fix/#219] navigationBar를 수정하였습니다.
  SplitIt/Presenter/History/View/Cell/HistorySplitCell.swift
  SplitIt/Presenter/History/ViewModel/HistorySplitCellVM.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix

#224 Fix/#223 NavigationBar 버튼 탭 시 색상이 변경되도록 수정하였습니다.
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix

#225 [Feat/#222] ExclItemEditModal의 삭제 버튼 및 Alert를 수정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
  SplitIt/Resources/Components/SPAlertController.swift
Labels: ✨ Feat, 🛠️ Fix

#227 [Feat/#226] Custom Keyboard 기기 대응 적용 완료했습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Presenter/CustomKeyboard/CustomKeyBoard.swift
  SplitIt/Presenter/CustomKeyboard/KeyboardButton.swift
  SplitIt/Presenter/CustomKeyboard/SecondVC.swift
  SplitIt/Presenter/CustomKeyboard/TestVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#229 [Design/#228] Editflow에 textColor가 지정되지 않은 컴포넌트를 수정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/EditCSListView/EditCSListVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSListView/EditCSListVM.swift
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailCell.swift
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailVC.swift
  SplitIt/Resources/Components/DefaultEditButton.swift
Labels: 🎨 Design

#232 Design/#230 다크모드관련 textcolor 수정
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: 🎨 Design

#234 233 design 추가적인 textcolor 수정
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: 🎨 Design

#236 [Design/#231] SPTextField의 placeHolder에 color를 지정합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailVC.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: 🎨 Design

#237 [Feat/#233] CustomKeyboard 백스페이스 계속 누르면 연달아 지워지는 기능 구현
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Presenter/CustomKeyboard/CustomKeyBoard.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#240 [Feat/#239] SPTextField의 text의 editingEnd일 때를 구독하여 양 끝 공백을 제거합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Resources/Components/SPTextField.swift
Labels: ✨ Feat

#243 [Feat/#242] SPTextfield의 clearbuttonMode를 활성화합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: ✨ Feat, 🛠️ Fix

#245 [Feat/#241] SplitRepository에 csInfo가 생성될 때 title의 기본값(1차, 2차 등)을 자동으로 설정하는 기능을 추가하였습니다.
  SplitIt/Models/LocalModels/CSInfo.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Repository/SplitRepository.swift
Labels: ✨ Feat

#246 [Fix/#244] SPTextfield의 기본 font를 적용합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitEditFlow/JSDetailView/JSDetailVC.swift
  SplitIt/Presenter/SplitEditFlow/NewEditFlowViews/EditCSInfo/EditCSInfoVC.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: 🛠️ Fix

#248 Fix/#247 QA에서 발견한 문제점을 수정하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt/Presenter/History/View/HistoryVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Repository/SplitRepository.swift
Labels: 🛠️ Fix

#250 238 fix mybankaccountview 수정
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Presenter/CustomKeyboard/KeyboardButton.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/BankListData.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: ✨ Feat

#253 [Feat/#252] CSInfo의 firstresponder를 변경합니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: ✨ Feat, 🛠️ Fix

#255 [Fix/#254] SPTextField의 num을 입력하는 곳의 기본 값을 빈 값으로 변경합니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoAddModalVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
  SplitIt/Presenter/SplitEditFlow/NewEditFlowViews/EditCSInfo/EditCSInfoVM.swift
Labels: 🛠️ Fix

#259 Feat/#249 CSMember와 CSMemberSearch를 합친 NewCSMember를 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/NewCSMember/View/Cell/CSMemberEmptyBackGroundView.swift
  SplitIt/Presenter/SplitCreateFlow/NewCSMember/View/Cell/CSMemberSearchCell.swift
  SplitIt/Presenter/SplitCreateFlow/NewCSMember/View/Cell/CSMemberSelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/NewCSMember/View/NewCSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/NewCSMember/ViewModel/NewCSMemberVM.swift
Labels: ✨ Feat

#261 Fix/#251 fix myinfoandmybankaccount
  .DS_Store
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Presenter/CustomKeyboard/CustomKeyBoard.swift
  SplitIt/Presenter/CustomKeyboard/KeyboardButton.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/ViewModel/MemberLogVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/BankListData.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: 🛠️ Fix

#268 Feat/#266 toast message library를 도입하고 splitShareVC에 적용하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt/Presenter/SplitCreateFlow/CSMember/Model/MemberCheck.swift
  SplitIt/Presenter/SplitShare/Model/CSMemberResult.swift
  SplitIt/Presenter/SplitShare/Model/SplitResult.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
Labels: ✨ Feat

#271 Feat/#269 MyInfo를 입력 안했을 시 SplitShareVC에서 PopUp이 뜨도록 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Assets.xcassets/Images/PopUp/Contents.json
  SplitIt/Assets.xcassets/Images/PopUp/GoToMyInfo.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/PopUp/GoToMyInfo.imageset/GoToMyInfo@1x.png
  SplitIt/Assets.xcassets/Images/PopUp/GoToMyInfo.imageset/GoToMyInfo@2x.png
  SplitIt/Assets.xcassets/Images/PopUp/GoToMyInfo.imageset/GoToMyInfo@3x.png
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Resources/Components/SPPopUp.swift
Labels: ✨ Feat

#273 Fix/#267 keyboard refactor andmybankaccount
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/ViewModel/MemberLogVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
  SplitIt/Resources/Utility/CustomKeyboard/AccountCustomkeyboard.swift
  SplitIt/Resources/Utility/CustomKeyboard/CustomKeyBoard.swift
  SplitIt/Resources/Utility/CustomKeyboard/KeyboardButton.swift
Labels: 🛠️ Fix

#278 Fix/#275 mybankaccount hi fi
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/ViewModel/MemberLogVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/BankListData.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: 🛠️ Fix

#277 Fix/#272 SplitRepository 및 RealmManage 수정
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Models/CSInfo.swift
  SplitIt/Models/CSMember.swift
  SplitIt/Models/ExclItem.swift
  SplitIt/Models/ExclMember.swift
  SplitIt/Models/LocalModels/CSInfo.swift
  SplitIt/Models/LocalModels/CSMember.swift
  SplitIt/Models/LocalModels/ExclItem.swift
  SplitIt/Models/LocalModels/ExclMember.swift
  SplitIt/Models/LocalModels/MemberLog.swift
  SplitIt/Models/LocalModels/Split.swift
  SplitIt/Models/MemberLog.swift
  SplitIt/Models/RealmModels/RealmCSInfo.swift
  SplitIt/Models/RealmModels/RealmCSMember.swift
  SplitIt/Models/RealmModels/RealmExclItem.swift
  SplitIt/Models/RealmModels/RealmExclMember.swift
  SplitIt/Models/RealmModels/RealmMemberLog.swift
  SplitIt/Models/RealmModels/RealmSplit.swift
  SplitIt/Models/Split.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Realm/Entity/Convertion/LocalConvertibleType.swift
  SplitIt/Realm/Entity/Convertion/RealmRepresentable.swift
  SplitIt/Realm/Entity/RMCSInfo.swift
  SplitIt/Realm/Entity/RMCSMember.swift
  SplitIt/Realm/Entity/RMExclItem.swift
  SplitIt/Realm/Entity/RMExclMember.swift
  SplitIt/Realm/Entity/RMMemberLog.swift
  SplitIt/Realm/Entity/RMSplit.swift
  SplitIt/Realm/Realm+.swift
  SplitIt/Repository/RealmManager.swift
  SplitIt/Repository/SplitRepository.swift
Labels: 🛠️ Fix

#284 [Fix/#282] 자잘한 수정사항들을 수정하였습니다.
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyActive.imageset/CurrencyActive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyActive.imageset/CurrencyActive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyActive.imageset/CurrencyActive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyDeactive.imageset/CurrencyDeactive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyDeactive.imageset/CurrencyDeactive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/CurrencyDeactive.imageset/CurrencyDeactive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueActive.imageset/ElseValueActive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueActive.imageset/ElseValueActive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueActive.imageset/ElseValueActive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueDeactive.imageset/ElseValueDeactive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueDeactive.imageset/ElseValueDeactive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/ElseValueDeactive.imageset/ElseValueDeactive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberActive.imageset/MemberActive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberActive.imageset/MemberActive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberActive.imageset/MemberActive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberDeactive.imageset/MemberDeactive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberDeactive.imageset/MemberDeactive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/MemberDeactive.imageset/MemberDeactive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagActive.imageset/TagActive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagActive.imageset/TagActive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagActive.imageset/TagActive@3x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagDeactive.imageset/TagDeactive@1x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagDeactive.imageset/TagDeactive@2x.png
  SplitIt/Assets.xcassets/Images/ProgressGuide/TagDeactive.imageset/TagDeactive@3x.png
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@1x.png
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@2x.png
  SplitIt/Assets.xcassets/Images/Symbols/DeleteIcon/DeleteIconTypeD.imageset/DeleteIconTypeD@3x.png
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberSearchCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/ViewModel/ExclItemInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/ViewModel/ExclItemInfoEditModalVM.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Repository/RealmManager.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix

#288 Design/#287 design excliteminputmodal hifi
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemAddCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputEmptyView.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/Cell/ExclItemInfoDeactiveModalCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/Cell/ExclItemInfoModalCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Resources/Extensions/UIColor+.swift
  SplitIt/Resources/Extensions/UILabel+.swift
Labels: 🛠️ Fix, 🎨 Design

#292 [Feat/#289] SplitMethodSecect View의 Hi-fi Design 적용
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Assets.xcassets/SplitMethod/Contents.json
  SplitIt/Assets.xcassets/SplitMethod/EqualSplitMethodIcon.imageset/Contents.json
  SplitIt/Assets.xcassets/SplitMethod/EqualSplitMethodIcon.imageset/EqualSplitMethodIcon@1x.png
  SplitIt/Assets.xcassets/SplitMethod/EqualSplitMethodIcon.imageset/EqualSplitMethodIcon@2x.png
  SplitIt/Assets.xcassets/SplitMethod/EqualSplitMethodIcon.imageset/EqualSplitMethodIcon@3x.png
  SplitIt/Assets.xcassets/SplitMethod/SmartSplitMethodIcon.imageset/Contents.json
  SplitIt/Assets.xcassets/SplitMethod/SmartSplitMethodIcon.imageset/SmartSplitMethodIcon@1x.png
  SplitIt/Assets.xcassets/SplitMethod/SmartSplitMethodIcon.imageset/SmartSplitMethodIcon@2x.png
  SplitIt/Assets.xcassets/SplitMethod/SmartSplitMethodIcon.imageset/SmartSplitMethodIcon@3x.png
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/Cell/SplitMethodCell.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethod.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/ViewModel/SplitMethodSelectVM.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix, 🎨 Design

#297 [Feat/#286] 영수증 서체 ttf 파일 추가와 숫자 및 영수증 서체에 Design Token을 적용한 UIFont+ 신규 Class 추가
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Info.plist
  SplitIt/Resources/Assets/Fonts/Receipt/EliceDigitalCodingVerHBold.ttf
  SplitIt/Resources/Assets/Fonts/Receipt/EliceDigitalCodingVerHRegular.ttf
  SplitIt/Resources/Extensions/UIFont+.swift
Labels: ✨ Feat

#299 [Design/#298] 앱 아이콘을 신규 디자인으로 변경하였습니다.
  SplitIt/Assets.xcassets/AppIcon.appiconset/Contents.json
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon-App-iTunes.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_114×114.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_120x120.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_120×120.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_128x128.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_136x136.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_152x152.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_167x167.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_180×180.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_192×192.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_40x40.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_58x58.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_60×60.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_76x76.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_80x80.png
  SplitIt/Assets.xcassets/AppIcon.appiconset/Icon_87×87.png
Labels: 🎨 Design

#301 [Design/#293] HomeView에 Design Hi-fi를 적용합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/seungwan.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Assets.xcassets/Images/Home/SplitBeginArrow/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitBeginArrow/SplitBeginArrow.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitBeginArrow/SplitBeginArrow.imageset/SplitBeginArrow@1x.png
  SplitIt/Assets.xcassets/Images/Home/SplitBeginArrow/SplitBeginArrow.imageset/SplitBeginArrow@2x.png
  SplitIt/Assets.xcassets/Images/Home/SplitBeginArrow/SplitBeginArrow.imageset/SplitBeginArrow@3x.png
  SplitIt/Assets.xcassets/Images/Home/SplitInfoIcon/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitInfoIcon/SplitInfoIcon.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitInfoIcon/SplitInfoIcon.imageset/SettingIcon@1x.png
  SplitIt/Assets.xcassets/Images/Home/SplitInfoIcon/SplitInfoIcon.imageset/SettingIcon@2x.png
  SplitIt/Assets.xcassets/Images/Home/SplitInfoIcon/SplitInfoIcon.imageset/SettingIcon@3x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitImageLogo.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitImageLogo.imageset/SplitImageLogo@1x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitImageLogo.imageset/SplitImageLogo@2x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitImageLogo.imageset/SplitImageLogo@3x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitTitleLogo.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitTitleLogo.imageset/SplitTitleLogo@1x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitTitleLogo.imageset/SplitTitleLogo@2x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitTitleLogo.imageset/SplitTitleLogo@3x.png
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Resources/Components/SPButton.swift
Labels: 🎨 Design

#306 [Feat/#303] [Num, NumRounded, Korean]의 Light와 Bold 스타일에 따른 Class를 추가하고 각각에 대한 주석들을 업데이트하였습니다.
  SplitIt/Resources/Extensions/UIFont+.swift
Labels: ✨ Feat

#308 [Feat/#304] EditFlow에 SwipeBack 기능을 적용합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSExclItem/View/EditExclItemInputVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSExclItem/ViewModel/EditExclItemInputVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSInfo/View/EditCSInfoVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSInfo/ViewModel/EditCSInfoVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/NewEditCSMember/View/NewEditCSMemberVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/NewEditCSMember/ViewModel/NewEditCSMemberVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSItem/View/EditCSItemVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSList/View/EditCSListVC.swift
Labels: ✨ Feat, 🛠️ Fix

#311 Fix/#310 myinfo andmybank detail
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/ViewModel/MemberLogVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/BankListData.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: 🛠️ Fix

#312 [Feat/#309] ExclItem Modal에 의한 Notificaiton을 정의합니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSExclItem/View/EditExclItemInputVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSExclItem/ViewModel/EditExclItemInputVM.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
  SplitIt/Resources/Extensions/Notification+.swift
Labels: ✨ Feat, 🛠️ Fix

#314 [Design/#313] CreateFlow의 Font에 Hi-fi를 적용합니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/Cell/SplitMethodCell.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/View/EditCSMemberVC.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: 🎨 Design

#318 [Feat/#316] UIColor+에 Darken Colors와 그에 따른 Navigation Text Button Color Token들을 추가하고, 색상 순서 및 주석들을 수정하였습니다.
  SplitIt/Resources/Extensions/UIColor+.swift
Labels: ✨ Feat

#319 [Fix/#317] 백제스쳐 변경 완료했습니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: 🛠️ Fix

#320 Desing/#305 SplitShareVC 디자인 수정하였습니다.
  SplitIt/Assets.xcassets/Images/Receipt/Contents.json
  SplitIt/Assets.xcassets/Images/Receipt/Receipt.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Receipt/Receipt.imageset/Receipt@1x.png
  SplitIt/Assets.xcassets/Images/Receipt/Receipt.imageset/Receipt@2x.png
  SplitIt/Assets.xcassets/Images/Receipt/Receipt.imageset/Receipt@3x.png
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionFooter.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Resources/Extensions/UILabel+.swift
Labels: 🎨 Design

#322 Fix/#321 필요에 따라 Flow별 header를 바꿔주도록 하였습니다.
  SplitIt/Presenter/HistoryFlow/ViewModel/HistoryVM.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
Labels: 🛠️ Fix

#324 Design/#323 history 뷰의 디자인을 수정하였습니다.
  SplitIt/Presenter/HistoryFlow/View/Cell/HistorySplitCell.swift
  SplitIt/Presenter/HistoryFlow/View/HistorySectionHeader.swift
  SplitIt/Presenter/HistoryFlow/View/HistoryVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: 🎨 Design

#326 [Feat/#325] UIColor+에 Surface Secondary의 Pressed Color를 추가하였습니다.
  SplitIt/Resources/Extensions/UIColor+.swift
Labels: ✨ Feat

#330 [Design/#329] SPButton의 홈화면 버튼의 디자인을 수정하고 SurfaceSecondary의 색상 스타일 추가하였습니다.
  SplitIt/Resources/Components/SPButton.swift
Labels: 🎨 Design

#331 Fix/#328 fixuserdefaults andcustomkeyboard
  .DS_Store
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/BankListModalVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
  SplitIt/Resources/Utility/CustomKeyboard/KeyboardButton.swift
Labels: 🛠️ Fix

#333 Fix/#327 출시 전 기타 수정사항들을 수정합니다.
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSInfo/View/EditCSInfoVC.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionFooter.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Resources/Extensions/UIFont+.swift
  SplitIt/Resources/Extensions/UILabel+.swift
Labels: 🛠️ Fix

#335 Design/#334 SplitShare에서 버튼 색상을 수정하였습니다.
  SplitIt/Assets.xcassets/Images/Symbols/SplitEditIcon/Contents.json
  SplitIt/Assets.xcassets/Images/Symbols/SplitEditIcon/SplitEditIcon.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Symbols/SplitEditIcon/SplitEditIcon.imageset/SplitEditIcon@1x.png
  SplitIt/Assets.xcassets/Images/Symbols/SplitEditIcon/SplitEditIcon.imageset/SplitEditIcon@2x.png
  SplitIt/Assets.xcassets/Images/Symbols/SplitEditIcon/SplitEditIcon.imageset/SplitEditIcon@3x.png
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Resources/Components/SPButton.swift
Labels: 🎨 Design

#337 Fix/#336 splitshare 버튼 디자인 및 팝업 로직을 수정하였습니다.
  SplitIt/Presenter/HistoryFlow/ViewModel/HistoryVM.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
Labels: 🛠️ Fix

#342 [Fix/#341] EditCSMember 검색창 초과입력시 버그 수정 및 list 수정 ?
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/juhwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/ViewModel/EditCSMemberVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSList/View/EditCSListVC.swift
Labels: 🐛 Bug, 🛠️ Fix

#344 [Fix/#343] SPAlertController의 AutoLayout을 Device Height 비율에 맞게 변경합니다
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Resources/Components/SPAlertController.swift
Labels: 🛠️ Fix

#349 Design/#345 design qa
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Resources/Utility/CustomKeyboard/KeyboardButton.swift
Labels: 🎨 Design

#350 [Design/#348] CreateFlow의 디자인 디테일을 수정합니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/Cell/ExclItemCell.swift
  SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/Cell/SplitMethodCell.swift
Labels: 🛠️ Fix

#352 Design/#347 디자인 디테일 수정 완료하였습니다.
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@3x.png
  SplitIt/Presenter/HistoryFlow/View/Cell/HistorySplitCell.swift
  SplitIt/Presenter/HistoryFlow/View/HistoryVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/View/EditCSMemberVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/ViewModel/EditCSMemberVM.swift
Labels: 🎨 Design

#353 346 design editflow design 수정
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/juhwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSExclItem/View/EditExclItemInputVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSItem/View/EditCSItemVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSList/View/Cell/EditCSListCell.swift
Labels: 🎨 Design

#354 [Design/#351] 디자인 QA tableView 간격 수정 완료했습니다.
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
Labels: 🎨 Design

#358 Design/#355 디자인 QA 적용 완료하였습니다.
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberSelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/View/EditCSMemberVC.swift
  SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/ViewModel/EditCSMemberVM.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
Labels: 🎨 Design

#360 [Design/#357] 디자인 QA 수정 완료했습니다.
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: 🎨 Design

#361 수정 완료했습니다.
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
Labels: 🎨 Design

#362 수정 완료했습니다.
  .DS_Store
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/.DS_Store
Labels: 🎨 Design

#369 [Fix/#364] 코드 리팩토링했습니다.
  SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: 🛠️ Fix

#371 [Feat/#370] iPhone Mini 서체 최적화를 위하여 UIDevice+, UIFont+를 수정하였습니다
  SplitIt/Resources/Extensions/UIDevice+.swift
  SplitIt/Resources/Extensions/UIFont+.swift
Labels: ✨ Feat
