Repository DeveloperAcademy-POSTECH/MacC-Team13-SplitIt, pull requests merged in 2023-10, with the labels that each got.

#2 Feat/#1 HomeVC를 세팅하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Resources/Extensions/UIColor+.swift
  SplitIt/Resources/Extensions/UITextField+.swift
  SplitIt/SceneDelegate.swift
  SplitIt/ViewController.swift
Labels: ✨ Feat

#5 Feat/#3 CSTitleInput, CSTotalAmount 뷰를 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/NavigationHeader.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/ViewModel/CSTitleInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/ViewModel/CSTotalAmountInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CreateStore.swift
  SplitIt/Resources/NumberFormatterHelper.swift
  SplitIt/SceneDelegate.swift
Labels: ✨ Feat

#7 Feat/#6 CSMemberInput 뷰를 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Assets.xcassets/CSFlow/Contents.json
  SplitIt/Assets.xcassets/CSFlow/XMark.imageset/Contents.json
  SplitIt/Assets.xcassets/CSFlow/XMark.imageset/xMark.png
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputSearchFooter.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberInputCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberInputSearchCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/ViewModel/CSTitleInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift
Labels: ✨ Feat

#11 Feat/#10 Realm, Local Model 추가하였습니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/zerom.xcuserdatad/xcschemes/xcschememanagement.plist
  SplitIt/Models/LocalModels/CSInfo.swift
  SplitIt/Models/LocalModels/CSMember.swift
  SplitIt/Models/LocalModels/ExclItem.swift
  SplitIt/Models/LocalModels/ExclMember.swift
  SplitIt/Models/LocalModels/Split.swift
  SplitIt/Models/RealmModels/RealmCSInfo.swift
  SplitIt/Models/RealmModels/RealmCSMember.swift
  SplitIt/Models/RealmModels/RealmExclItem.swift
  SplitIt/Models/RealmModels/RealmExclMember.swift
  SplitIt/Models/RealmModels/RealmSplit.swift
Labels: ✨ Feat

#13 Feat/#12 realmmanager 생성 및 작성하였습니다.
  .DS_Store
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Repository/RealmManager.swift
Labels: ✨ Feat

#15 Feat/#14 SplitRepository 생성 및 정리하였습니다.
  .DS_Store
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Repository/RealmManager.swift
  SplitIt/Repository/SplitRepository.swift
Labels: ✨ Feat

#17 Feat/#16 친구검색기록을 위한 MemberLog, RealmMemberLog 추가 및 관련 메서드 작성하였습니다.
  .DS_Store
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Models/LocalModels/MemberLog.swift
  SplitIt/Models/RealmModels/RealmMemberLog.swift
  SplitIt/Repository/RealmManager.swift
  SplitIt/Repository/SplitRepository.swift
Labels: ✨ Feat

#22 Feat/#18 HomeView 기본 레이아웃을 수정하였습니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
Labels: ✨ Feat

#30 [Feat/#29] MyInfoVC, MyInfoVM 구현했음
  SplitIt/Presenter/MyInfo/PayData.swift
  SplitIt/Presenter/MyInfo/SocialPay.swift
  SplitIt/Presenter/MyInfo/User.swift
  SplitIt/Presenter/MyInfo/UserData.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
Labels: ✨ Feat

#37 Feat/#27 SplitRepository를 CreateFlow에 적용하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberInputCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberConfirmHeaderVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberConfirmVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/ViewModel/CSTitleInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/ViewModel/CSTotalAmountInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/ExclMemberSection.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/ExclMemberSectionHeader.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/View/Cell/ExclMemberCell.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/View/ExclMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/ViewModel/ExclMemberVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemName/View/ExclItemNameInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemName/ViewModel/ExclItemNameInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemPrice/ViewModel/ExclItemPriceInputVM.swift
Labels: ✨ Feat

#48 Feat/#47 Pressed Button만을 위한 Color Design Token을 추가하고, 해당 토큰을 SPButton에 적용하였습니다.
  SplitIt/Resources/Components/SPButton.swift
  SplitIt/Resources/Extensions/UIColor+.swift
Labels: ✨ Feat

#50 Fix/#49 SmartSplitIconDeactivate 이미지에셋을 교체하였습니다,.
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SmartSplitIconDeactivate@1x.png
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SmartSplitIconDeactivate@2x.png
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SmartSplitIconDeactivate@3x.png
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SplitIconDeactivate@1x.png
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SplitIconDeactivate@2x.png
  SplitIt/Assets.xcassets/Images/HalfButton/SmartSplitIcon/SmartSplitIconDeactivate.imageset/SplitIconDeactivate@3x.png
Labels: 🛠️ Fix

#53 feat/#51 작은 버튼 디자인 규격의 추가에 따른 design token 및 component의 추가
  SplitIt/Resources/Components/SPButton.swift
  SplitIt/Resources/Extensions/UIFont+.swift
Labels: ✨ Feat

#55 [Feat/#54] MyInfoView 모두 수정완료. MyInfo 텅뷰 완성
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfo/MyInfoEmptyVC.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#63 Feat/#61 design memberlogview
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/ViewModel/MemberLogVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#65 [Design] CreateFlow 앞부분 UI Detail 수정하였습니다
  .DS_Store
  SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmHeader.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberConfirmCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberConfirmHeaderVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/SPButton.swift
Labels: 🎨 Design

#68 Design/#64 design pre setting
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/MyInfo/MyInfoEmptyVC.swift
  SplitIt/Presenter/MyInfo/PayData.swift
  SplitIt/Presenter/MyInfo/SocialPay.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/Cell/BankCell.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/ClearButton.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/PayButton.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: ✨ Feat

#73 [Design/#72] 이미지 에셋들을 추가하였습니다.
  SplitIt/Assets.xcassets/Images/Home/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SmartSplitIconWhite/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SmartSplitIconWhite/SmartSplitIconWhite.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SmartSplitIconWhite/SmartSplitIconWhite.imageset/SmartSplitIconWhite.png
  SplitIt/Assets.xcassets/Images/Home/SmartSplitIconWhite/SmartSplitIconWhite.imageset/SmartSplitIconWhite@2x.png
  SplitIt/Assets.xcassets/Images/Home/SmartSplitIconWhite/SmartSplitIconWhite.imageset/SmartSplitIconWhite@3x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitItLogo.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitItLogo.imageset/SplitItLogo.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitItLogo.imageset/SplitItLogo@2x.png
  SplitIt/Assets.xcassets/Images/Home/SplitItLogo/SplitItLogo.imageset/SplitItLogo@3x.png
  SplitIt/Assets.xcassets/Images/SplashImage/Contents.json
  SplitIt/Assets.xcassets/Images/SplashImage/SplashImage.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/SplashImage/SplashImage.imageset/SplashImage.png
  SplitIt/Assets.xcassets/Images/SplashImage/SplashImage.imageset/SplashImage@2x.png
  SplitIt/Assets.xcassets/Images/SplashImage/SplashImage.imageset/SplashImage@3x.png
Labels: 🎨 Design

#74 [Design/#69] 수정된 HomeView 수정 완료했습니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: 🎨 Design

#79 Design/#75 homeview detail design
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
Labels: 🎨 Design

#81 [Design/#77] MyInfoVC MyInfoDetail vcs design detail
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/PayButton.swift
Labels: 🎨 Design

#83 [Feat/#80] 런치스크린에 splashImage 넣었습니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Base.lproj/LaunchScreen.storyboard
  SplitIt/Presenter/SplashVC.swift
Labels: ✨ Feat

#85 Design/#84 social pay btn setting
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/Cell/MemberCell.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/PayButton.swift
Labels: ✨ Feat, 🎨 Design

#90 [Feat/#89] NaviHeader 적용완료. MyInfo Layout 깨지던 거 해결
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#93 [Design/#92] Create Flow 각 TextField 하단의 UX Writing을 수정하였습니다.
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemName/View/ExclItemNameInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemPrice/View/ExclItemPriceInputVC.swift
Labels: 🎨 Design

#95 [Feat/#91] alert창 뷰 구현
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/AlertView/View/AccountAlertVC.swift
  SplitIt/Presenter/AlertView/View/CustomAlertVC.swift
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
Labels: ✨ Feat

#100 Feat/#96 alert connect
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/AlertView/AlertController.swift
  SplitIt/Presenter/AlertView/View/CustomAlertVC.swift
  SplitIt/Presenter/AlertView/View/SecondVC.swift
  SplitIt/Presenter/AlertView/View/TestVC.swift
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemMember/ExclMemberSectionHeader.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclPageController/ExclPageController.swift
Labels: ✨ Feat

#104 [Fix/#103] 홈화면에서 CSEditListVC 이동하는 코드 주석처리 하였습니다.
  SplitIt/Presenter/Home/View/HomeVC.swift
Labels: 🛠️ Fix

#105 Feat/#102 ResultView의 UI 디자인을 적용하였습니다.
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Result/View/Cell/AddSplitHeader.swift
  SplitIt/Presenter/Result/View/Cell/ResultCell.swift
  SplitIt/Presenter/Result/View/Cell/ResultExclItemCell.swift
  SplitIt/Presenter/Result/View/ResultSectionFooter.swift
  SplitIt/Presenter/Result/View/ResultSectionHeader.swift
  SplitIt/Presenter/Result/View/ResultVC.swift
  SplitIt/Resources/Components/NavigationBar.swift
Labels: 🎨 Design

#107 [Feat/#58] SplitShareView 구현하였습니다
  .DS_Store
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitShare/CSMemberResult.swift
  SplitIt/Presenter/SplitShare/SplitMemberResult.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Resources/Extensions/UIView+.swift
Labels: 🎨 Design

#108 Revert "[Feat/#58] SplitShareView 구현하였습니다"
  .DS_Store
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitShare/CSMemberResult.swift
  SplitIt/Presenter/SplitShare/SplitMemberResult.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Resources/Extensions/UIView+.swift
Labels: 🐛 Bug

#109 Feat/#106 Splitshareview와 ResultView를 연결합니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/History/View/HistoryVC.swift
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Result/View/ResultVC.swift
  SplitIt/Presenter/Result/ViewModel/ResultVM.swift
  SplitIt/Presenter/SplitShare/CSMemberResult.swift
  SplitIt/Presenter/SplitShare/SplitResult.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Components/NavigationBar.swift
  SplitIt/Resources/Extensions/UIView+.swift
Labels: ✨ Feat

#113 Fix/#112 fix createflow fetch back
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Result/View/ResultVC.swift
  SplitIt/Presenter/Result/ViewModel/ResultVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmHeader.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberConfirmVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclPageController/ExclPageController.swift
  SplitIt/Resources/Components/NavigationBar.swift
Labels: 🛠️ Fix

#115 [Feat/#110] 버튼 눌림효과 수정. '따로 먹은 항목들' 버튼 삭제
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/Home/ViewModel/HomeVM.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
Labels: ✨ Feat

#118 [Fix/#111 splitshareview 버그 수정 및 기존 비즈니스 로직 수정하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/zerom.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/NavigationHeader.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberInputCell.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
  SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
  SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
  SplitIt/Repository/SplitRepository.swift
  SplitIt/Resources/Extensions/UITableView+.swift
Labels: 🛠️ Fix

#120 [Feat/#116] SPbutton.swift를 복제한 NewSPButton.swift을 생성하여 리팩토링하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Resources/Components/NewSPButton.swift
Labels: ✨ Feat

#123 Design #114 applying design createflow
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Assets.xcassets/CSFlow/Contents.json
  SplitIt/Assets.xcassets/CSFlow/XMark.imageset/Contents.json
  SplitIt/Assets.xcassets/CSFlow/XMark.imageset/xMark.png
  SplitIt/Presenter/Result/View/Cell/ResultCell.swift
  SplitIt/Presenter/Result/View/ResultSectionHeader.swift
  SplitIt/Presenter/Result/View/ResultVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberConfirmVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberInputCell.swift
  SplitIt/Presenter/SplitEditFlow/CSExclItemMemberEdit/ExclMemberEditSectionHeader.swift
  SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift
Labels: 🎨 Design

#125 Feat/#122 mybankaccountviewscroll
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/chaewon.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt.xcodeproj/xcuserdata/chaewon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SplitIt/Presenter/AlertView/CustomKeyBoard.swift
  SplitIt/Presenter/AlertView/View/KeyboardButton.swift
  SplitIt/Presenter/AlertView/View/SecondVC.swift
  SplitIt/Presenter/AlertView/View/TestVC.swift
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/MyInfo/View/MyInfoVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
  SplitIt/Presenter/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
Labels: ✨ Feat

#127 Design/#119 HistoryView Design 작업을 완료하였습니다.
  SplitIt/Presenter/History/View/Cell/HistorySplitCell.swift
  SplitIt/Presenter/History/View/HistorySectionHeader.swift
  SplitIt/Presenter/History/View/HistoryVC.swift
  SplitIt/Presenter/History/ViewModel/HistoryVM.swift
Labels: 🎨 Design

#129 Feat/#124 createflow의 ux fix
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTitle/ViewModel/CSTitleInputVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/ViewModel/CSTotalAmountInputVM.swift
Labels: ✨ Feat

#133 Feat/#130 CSInfoView를 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt.xcodeproj/project.xcworkspace/xcuserdata/seungwan.xcuserdatad/UserInterfaceState.xcuserstate
  SplitIt/Presenter/Home/View/HomeVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Resources/Components/NewSPButton.swift
  SplitIt/Resources/Components/SPTextField.swift
Labels: ✨ Feat, 🎨 Design

#138 Feat/#128 CSMemberSearchView 구현하였습니다.
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/MemberCheck.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/CSMemberCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SearchCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift
  SplitIt/Repository/SplitRepository.swift
Labels: ✨ Feat

#147 Design/#146 HomeView Design 기기대응 완료하였습니다
  SplitIt/Presenter/Home/View/HomeVC.swift
Labels: 🎨 Design

#150 [Design] NaviHeader에서 SPNavigationBar로 전면 수정하였습니다
  SplitIt.xcodeproj/project.pbxproj
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateActive.imageset/CSInfoCreateActive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateActive.imageset/CSInfoCreateActive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateActive.imageset/CSInfoCreateActive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/CSInfoCreateDeactive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/CSInfoCreateDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateActive.imageset/ExclItemCreateActive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateActive.imageset/ExclItemCreateActive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateActive.imageset/ExclItemCreateActive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/ExclItemCreateDeactive.imageset/ExclItemCreateDeactive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateActive.imageset/MemberCreateActive@3x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@1x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@2x.png
  SplitIt/Assets.xcassets/Images/NavigationBar/MemberCreateDeactive.imageset/MemberCreateDeactive@3x.png
  SplitIt/Assets.xcassets/Images/Symbols/XMark/Contents.json
  SplitIt/Assets.xcassets/Images/Symbols/XMark/XMark.imageset/Contents.json
  SplitIt/Assets.xcassets/Images/Symbols/XMark/XMark.imageset/XMark@1x.png
  SplitIt/Assets.xcassets/Images/Symbols/XMark/XMark.imageset/XMark@2x.png
  SplitIt/Assets.xcassets/Images/Symbols/XMark/XMark.imageset/XMark@3x.png
  SplitIt/Presenter/SplitCreateFlow/CSInfo/View/CSInfoVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
  SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift
  SplitIt/Resources/Components/NaviHeader.swift
  SplitIt/Resources/Components/SPNavigationBar.swift
  SplitIt/Resources/Extensions/UIColor+.swift
Labels: 🎨 Design
